import Head from 'next/head'
import Navbarre from "./Navbarre"
import Footer from "./Footer"
const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Planfy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/img/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="preconnect" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet" />
      </Head>
      <Navbarre />
      <main>
        {children}
      </main>
      <Footer />
    </div>
  )
}

export default Layout
